#!/bin/bash

WORK_PATH='/Users/sofasuhova/Desktop/mipt/9sem/fedya/Logic_verification/DPI'

FMUL_SRC=`find $WORK_PATH/FMUL -name "*.v"`

#echo $FMUL_SRC

verilator -Wno-lint --binary --vpi -Wno-UNOPTFLAT \
    $WORK_PATH/src/top.sv \
    $WORK_PATH/src/func.c \
    -I $FMUL_SRC \
    -o test_bin